[package]
name = "order-submit"
version = "0.1.0"
authors = ["qiu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.3.4", features = ["full"] }
mini-redis = "0.3"
